export type WorkCategory = "artwork" | "client";

export interface WorkItem {
  slug: string;
  title: string;
  context: string;
  category: WorkCategory;
  src: string;
  width: number;
  height: number;
  video?: boolean;
}

export const works: WorkItem[] = [
  {
    slug: "new-music-friday",
    title: "New Music Friday",
    context: "Max FM 102.3 — social series",
    category: "client",
    src: "/work/work-new-music-friday.webp",
    width: 800,
    height: 800,
  },
  {
    slug: "crown-sketch",
    title: "Crown Study",
    context: "Chalk line work on black",
    category: "artwork",
    src: "/work/art-crown-sketch.webp",
    width: 778,
    height: 1000,
  },
  {
    slug: "innovation-fest",
    title: "Innovation Fest 4.0",
    context: "COCOMS event series — Caleb University",
    category: "client",
    src: "/work/work-innovation-fest.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "sosa",
    title: "Sosa Fruit Drink",
    context: "Product campaign visual",
    category: "client",
    src: "/work/work-sosa.webp",
    width: 640,
    height: 800,
  },
  {
    slug: "match-day",
    title: "Match Day",
    context: "Caleb University — sports poster",
    category: "client",
    src: "/work/work-match-day.webp",
    width: 1080,
    height: 1080,
  },
  {
    slug: "abcy2-lineup",
    title: "A Brand Called You 2.0",
    context: "Second-edition seminar — speaker lineup",
    category: "client",
    src: "/work/work-abcy2-lineup.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "cyberbully-kit",
    title: "#SayNoToCyberbullying",
    context: "Campaign identity & merch kit",
    category: "client",
    src: "/work/work-cyberbully-kit.webp",
    width: 960,
    height: 960,
  },
  {
    slug: "caravan",
    title: "Caravan",
    context: "Digital pattern artwork",
    category: "artwork",
    src: "/work/art-caravan.webp",
    width: 720,
    height: 812,
  },
  {
    slug: "jester-i",
    title: "The Jester — I",
    context: "Costume, makeup & photo direction",
    category: "artwork",
    src: "/work/art-jester-i.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "ojude-cocoms",
    title: "Ojudé COCOMS",
    context: "'A Mazobia Gathering' — cultural event flyer",
    category: "client",
    src: "/work/work-ojude-cocoms.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "spectrum-gaze",
    title: "Spectrum Gaze",
    context: "Digital abstract portrait",
    category: "artwork",
    src: "/work/art-spectrum-gaze.webp",
    width: 1024,
    height: 1536,
  },
  {
    slug: "tide-figure",
    title: "Tide Figure",
    context: "Acrylic abstract portrait",
    category: "artwork",
    src: "/work/art-tide-figure.webp",
    width: 810,
    height: 1080,
  },
  {
    slug: "sterling",
    title: "Bank With Confidence",
    context: "Sterling Bank — concept ad",
    category: "client",
    src: "/work/work-sterling.webp",
    width: 640,
    height: 800,
  },
  {
    slug: "innovation-fest-3",
    title: "Innovation Fest 3.0",
    context: "'The Lens with the Mic' — speaker flyer",
    category: "client",
    src: "/work/work-innovation-fest-3.webp",
    width: 720,
    height: 870,
  },
  {
    slug: "reel-ii",
    title: "Motion Reel",
    context: "Video design & editing",
    category: "client",
    src: "/work/reel-ii.mp4",
    width: 720,
    height: 1280,
    video: true,
  },
  {
    slug: "ascom-awards",
    title: "ASCOM Dinner & Awards",
    context: "ASCOM 2025 — gala night flyer",
    category: "client",
    src: "/work/work-ascom-awards.webp",
    width: 720,
    height: 727,
  },
  {
    slug: "jester-ii",
    title: "The Jester — II",
    context: "Rain study — photo direction",
    category: "artwork",
    src: "/work/art-jester-ii.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "abcy-seminar",
    title: "A Brand Called You",
    context: "Seminar flyer — speaker lineup",
    category: "client",
    src: "/work/work-abcy-seminar.webp",
    width: 900,
    height: 1080,
  },
  {
    slug: "battle-brands",
    title: "Battle of the Brands",
    context: "Campus tournament identity",
    category: "client",
    src: "/work/work-battle-brands.webp",
    width: 565,
    height: 799,
  },
  {
    slug: "city-mosaic",
    title: "City Mosaic",
    context: "Digital abstract composition",
    category: "artwork",
    src: "/work/art-city-mosaic.webp",
    width: 715,
    height: 1200,
  },
  {
    slug: "face-of-cocoms",
    title: "Face of COCOMS 2026",
    context: "Auditions flyer",
    category: "client",
    src: "/work/work-face-of-cocoms.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "rider",
    title: "Rider at Low Tide",
    context: "Photography",
    category: "artwork",
    src: "/work/art-rider.webp",
    width: 689,
    height: 954,
  },
  {
    slug: "ojude-style-guide",
    title: "Ojudé COCOMS — Style Guide",
    context: "300LVL colour & style direction",
    category: "client",
    src: "/work/work-ojude-style-guide.webp",
    width: 557,
    height: 375,
  },
  {
    slug: "underneath-rose",
    title: "Underneath the Rose",
    context: "Theatre production poster",
    category: "client",
    src: "/work/work-underneath-rose.webp",
    width: 603,
    height: 713,
  },
  {
    slug: "rose-ticket",
    title: "Underneath the Rose — Tickets",
    context: "Admit-one ticket design",
    category: "client",
    src: "/work/work-rose-ticket.webp",
    width: 720,
    height: 444,
  },
  {
    slug: "bellas",
    title: "Bella's Lifestyle",
    context: "Launch collage — coming soon",
    category: "client",
    src: "/work/work-bellas.webp",
    width: 794,
    height: 1123,
  },
  {
    slug: "minotech",
    title: "It's Weekend",
    context: "Minotech — social campaign",
    category: "client",
    src: "/work/work-minotech.webp",
    width: 800,
    height: 800,
  },
  {
    slug: "save-a-child",
    title: "Save a Child",
    context: "PRAD students' outreach campaign",
    category: "client",
    src: "/work/work-save-a-child.webp",
    width: 810,
    height: 1080,
  },
  {
    slug: "ascom-tee",
    title: "ASCOM Wordmark",
    context: "Logo & merch design",
    category: "client",
    src: "/work/work-ascom-tee.webp",
    width: 720,
    height: 860,
  },
  {
    slug: "jester-iii",
    title: "The Jester — III",
    context: "Fire study — photo direction",
    category: "artwork",
    src: "/work/art-jester-iii.webp",
    width: 866,
    height: 1080,
  },
  {
    slug: "protect-a-child",
    title: "Protect a Child Today",
    context: "Campaign logo design",
    category: "client",
    src: "/work/work-protect-a-child.webp",
    width: 1000,
    height: 1000,
  },
  {
    slug: "chroma-field",
    title: "Chroma Field",
    context: "Mixed-media abstract",
    category: "artwork",
    src: "/work/art-chroma-field.webp",
    width: 703,
    height: 774,
  },
  {
    slug: "ioni-cakes",
    title: "Ioni Cakes",
    context: "Bakery brand collage",
    category: "client",
    src: "/work/work-ioni-cakes.webp",
    width: 800,
    height: 640,
  },
  {
    slug: "make-me-author",
    title: "Make Me an Author 2.0",
    context: "Writing contest flyer",
    category: "client",
    src: "/work/work-make-me-author.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "cocis-trade-fair",
    title: "COCIS Trade Fair",
    context: "Campus market — event flyer",
    category: "client",
    src: "/work/work-cocis-trade-fair.webp",
    width: 762,
    height: 1080,
  },
  {
    slug: "reel-i",
    title: "Design in Motion",
    context: "Video design & editing",
    category: "client",
    src: "/work/reel-i.mp4",
    width: 640,
    height: 360,
    video: true,
  },
  {
    slug: "welcome-march",
    title: "Welcome to March",
    context: "New-month social post",
    category: "client",
    src: "/work/work-welcome-march.webp",
    width: 1080,
    height: 1080,
  },
  {
    slug: "brand-called-you-badge",
    title: "#BeTheBrand Badge",
    context: "A Brand Called You — seminar identity",
    category: "client",
    src: "/work/work-brand-called-you.webp",
    width: 645,
    height: 665,
  },
  {
    slug: "period-care",
    title: "Best Period Protection",
    context: "Product flyer design",
    category: "client",
    src: "/work/work-period-care.webp",
    width: 864,
    height: 1080,
  },
  {
    slug: "upstander",
    title: "#BeAnUpstander",
    context: "Digital safety campaign",
    category: "client",
    src: "/work/work-upstander.webp",
    width: 715,
    height: 714,
  },
  {
    slug: "elderly-fitness",
    title: "Exercise for the Elderly",
    context: "Health awareness flyer",
    category: "client",
    src: "/work/work-elderly-fitness.webp",
    width: 1080,
    height: 1080,
  },
  {
    slug: "giants-logo",
    title: "G.I.A.N.T.S",
    context: "Logo concept",
    category: "client",
    src: "/work/work-giants-logo.webp",
    width: 513,
    height: 486,
  },
  {
    slug: "abcy2-identity",
    title: "Own Your Identity",
    context: "A Brand Called You 2.0 — event identity",
    category: "client",
    src: "/work/work-abcy2-identity.webp",
    width: 386,
    height: 315,
  },
  {
    slug: "spawn-logo",
    title: "Spawn",
    context: "Wordmark concept",
    category: "client",
    src: "/work/work-spawn-logo.webp",
    width: 500,
    height: 500,
  },
  {
    slug: "freshers-banner",
    title: "Freshers' Week 2026",
    context: "SRC — large-format event banner",
    category: "client",
    src: "/work/work-freshers-banner.webp",
    width: 594,
    height: 321,
  },
];

export interface Project {
  title: string;
  role: string;
  description: string;
  deliverables: string;
}

export const projects: Project[] = [
  {
    title: "#SayNoToCyberbullying",
    role: "Lead Graphics Designer",
    description:
      "Visual identity and promotional assets for a student-led campaign against cyberbullying — from logo and merch to the full social rollout.",
    deliverables: "Campaign branding · social graphics · posters · merch",
  },
  {
    title: "ASCOM 2025",
    role: "Graphics Designer",
    description:
      "Official branding and promotional materials for the Association of Mass Communication Students, kept consistent across every platform.",
    deliverables: "Event branding · social graphics · digital assets",
  },
  {
    title: "Mass Art 3.0",
    role: "Creative Designer",
    description:
      "Visual identity and promotional campaign celebrating artistic expression and driving student participation.",
    deliverables: "Event branding · promo graphics · social content",
  },
  {
    title: "Mass Art 4.0",
    role: "Lead Brand Designer",
    description:
      "Led creative direction with a refreshed identity and a cohesive campaign that strengthened the event's brand presence.",
    deliverables: "Brand identity · event graphics · marketing assets",
  },
  {
    title: "Reflection 7.0",
    role: "Graphics Designer",
    description:
      "Identity and promotional materials for a student creative community event celebrating collaboration and artistic expression.",
    deliverables: "Event branding · posters · social graphics",
  },
  {
    title: "PRAD Campaign — Taking the Lead",
    role: "Brand & Campaign Designer",
    description:
      "Visual identity and communication materials with a consistent, impactful design system across all promotional channels.",
    deliverables: "Campaign branding · social graphics · digital assets",
  },
  {
    title: "A Brand Called You 1.0",
    role: "Lead Graphics Designer",
    description:
      "Complete visual identity for an entrepreneurship and personal-branding event empowering students through innovation.",
    deliverables: "Brand identity · event graphics · promo materials",
  },
  {
    title: "Ojudé COCOMS 2026",
    role: "Brand Designer",
    description:
      "Culturally inspired promotional designs blending traditional influences with contemporary style into a memorable identity.",
    deliverables: "Event branding · promo graphics · style guides",
  },
  {
    title: "Mass Comm Football Team",
    role: "Creative Designer · 2024–2025",
    description:
      "Match-day posters, player announcements and fixture graphics that carried the team's visual identity through the season.",
    deliverables: "Match posters · player graphics · digital content",
  },
  {
    title: "A Brand Called You 2.0",
    role: "Lead Brand Identity Designer",
    description:
      "Led creative direction for the second edition — a refined identity applied cohesively across print and digital.",
    deliverables: "Brand identity · social campaigns · print",
  },
  {
    title: "Freshers' Week 2026 — SRC",
    role: "Banner Designer",
    description:
      "Bold large-format banner welcoming incoming students — a prominent centrepiece of the event's identity.",
    deliverables: "Large-format event banner",
  },
];

export const disciplines = [
  "Graphic Design",
  "Abstract Art",
  "Digital Art",
  "Branding & Logo",
  "Concept Development",
  "Motion Design",
  "Video Editing",
];

export const experience = [
  {
    org: "TVC Communications",
    role: "Graphic Design Intern",
    period: "2025",
    notes: "Created broadcast-ready visual designs and collaborated with cross-functional production teams.",
  },
  {
    org: "Max FM 102.3",
    role: "Junior Graphic Designer / PR Intern",
    period: "2025",
    notes: "Designed social media templates and event branding for on-air campaigns like New Music Friday.",
  },
  {
    org: "LinkedIn Local — Caleb University",
    role: "Design Lead",
    period: "2024 — Present",
    notes: "Leads design projects end-to-end and mentors junior designers in the campus creative community.",
  },
  {
    org: "Caleb University — College of Communication & Media Studies",
    role: "Graphics Designer & Video Editor",
    period: "2023 — Present",
    notes: "Graphics for the sports team and creative department; video editing for the creative department since 2025.",
  },
];

export const education = {
  school: "Caleb University, Lagos",
  degree: "B.Sc. Mass Communication",
  period: "2023 — 2026 (in view)",
};

export const contact = {
  email: "ocenstarartworks@gmail.com",
  phone: "+234 810 919 0621",
  phoneHref: "tel:+2348109190621",
  whatsapp:
    "https://wa.me/2348109190621?text=Hello%20Abraham!%20I%20saw%20your%20portfolio%20and%20I%27d%20like%20to%20work%20with%20you.",
  location: "Lagos, Nigeria",
};
